
import React from 'react';

interface TermsAndPrivacyProps {
  onNavigateBack: () => void;
}

const TermsAndPrivacy: React.FC<TermsAndPrivacyProps> = ({ onNavigateBack }) => {
  return (
    <div className="max-w-3xl mx-auto bg-white/80 backdrop-blur-sm rounded-2xl shadow-lg p-6 md:p-8 border border-stone-200 animate-fade-in-up">
      <h2 className="text-3xl font-bold text-center text-emerald-800 mb-6">Terms & Privacy</h2>
      
      <div className="prose max-w-none text-stone-700">
        <h3 className="text-xl font-semibold text-stone-800 font-serif">Terms of Service</h3>
        <p>Welcome to Spoonbot AI. By using this application, you agree to these terms. This service is provided "as is" for personal, non-commercial use. The recipes are generated by an artificial intelligence and are for informational purposes only.</p>
        <ul>
          <li><strong>Content:</strong> All recipes are generated by AI. We do not guarantee the accuracy, safety, or suitability of any recipe. You are responsible for verifying ingredients and cooking instructions.</li>
          <li><strong>User Responsibility:</strong> You are responsible for your own health and safety. Always check for potential allergens and follow safe cooking practices. Spoonbot AI is not liable for any adverse reactions or kitchen mishaps.</li>
          <li><strong>Service Availability:</strong> We may modify or discontinue the service at any time without notice.</li>
        </ul>
        
        <h3 className="mt-8 text-xl font-semibold text-stone-800 font-serif">Privacy Policy</h3>
        <p>Your privacy is important to us. This policy explains what information we collect and how we use it.</p>
        <ul>
          <li><strong>Information We Collect:</strong> We do not collect or store any personal information, including the ingredients you enter. All processing happens in real-time.</li>
          <li><strong>API Usage:</strong> Your ingredient list and preferences are sent to the Google Gemini API to generate a recipe. This data is handled according to Google's privacy policy. We do not log these requests.</li>
          <li><strong>Cookies & Tracking:</strong> This application does not use cookies or any tracking technologies.</li>
        </ul>
        <p className="mt-4">Last Updated: {new Date().toLocaleDateString()}</p>
      </div>
      
      <div className="text-center mt-8">
        <button
          onClick={onNavigateBack}
          className="bg-emerald-600 text-white font-bold py-2 px-6 rounded-full shadow-md hover:bg-emerald-700 transition-all duration-300"
        >
          &larr; Back to App
        </button>
      </div>
    </div>
  );
};

export default TermsAndPrivacy;